# Config file for Trainer

# Datafiles
runname: acanet_bigtrain
datafolder: "/scratch/jiaqi006/others/Yaseen_CHSSUMF"
fold_dir: Y18_10_fold
n_folds: 10
# Device settings
device: cuda  # Device to use for training (cpu or cuda)

# Model configuration
model:
  model_name: acanet
  ch_in: 1
  latent_dim: 32
  embed_dim: 32
  embed_reps: 1
  attn_mlp_dim: 128
  trnfr_mlp_dim: 128
  trnfr_heads: 8 
  dropout: 0.2 
  trnfr_layers: 3 
  n_blocks: 1
  max_len: 10000
  final_layer: '1dE'
  out_class: 5

# Logging and visualization
log_interval: 2
n_epoch: 100

# Training and optimization parameters
batch_size: 5
num_workers: 4
pin_memory: true
optimizer:
  lr: 0.0005
  weight_decay: 0.0001
scheduler:
  step_size: 20
  gamma: 0.1

# Data transformation settings
transform:
  orig_freq: 8000
  new_freq: 8000


