# Config file for Trainer

# Datafiles
runname: M5_cv_Aug_DL
datafolder: "/scratch/jiaqi006/others/Yaseen_CHSSUMF"
fold_dir: Y18_10_fold
n_folds: 10

codec_augment: True
double_loss: True

pascal_dir: /scratch/jiaqi006/others/PASCAL
pascal_split_dir: ./pascal_lists
# Device settings
device: cuda  # Device to use for training (cpu or cuda)

# Model configuration
model:
  model_name: M5
  n_input: 1
  n_output: 35
  stride: 16
  n_channel: 32

# Logging and visualization
log_interval: 2
n_epoch: 50

# Training and optimization parameters
batch_size: 5
num_workers: 4
pin_memory: true
optimizer:
  lr: 0.0005
  weight_decay: 0.0001
scheduler:
  step_size: 20
  gamma: 0.1

# Data transformation settings
transform:
  orig_freq: 8000
  new_freq: 2000


