# Config file for Trainer

# Datafiles
runname: "testWav2Vec"
datafolder: "/scratch/jiaqi006/others/Yaseen_CHSSUMF"
train_list: "./split_lists/training_2.txt"
valid_list: "./split_lists/testing_2.txt" #Change this to a proper validation dataset later. Or use K-fold.
test_list: "./split_lists/testing_2.txt"
# Device settings
device: cuda  # Device to use for training (cpu or cuda)

# Model configuration
model: wav2vec

# Logging and visualization
log_interval: 20
n_epoch: 8

# Training and optimization parameters
batch_size: 25
num_workers: 4
pin_memory: true
optimizer:
  lr: 0.0005
  weight_decay: 0.0001
scheduler:
  step_size: 20
  gamma: 0.1

# Data transformation settings
transform:
  orig_freq: 8000
  new_freq: 8000


